/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesTestingRouteImport } from './routes/services.testing'
import { Route as ServicesStaffingRouteImport } from './routes/services.staffing'
import { Route as ServicesMobileRouteImport } from './routes/services.mobile'
import { Route as ServicesFullStackRouteImport } from './routes/services.full-stack'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTestingRoute = ServicesTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesStaffingRoute = ServicesStaffingRouteImport.update({
  id: '/staffing',
  path: '/staffing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMobileRoute = ServicesMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFullStackRoute = ServicesFullStackRouteImport.update({
  id: '/full-stack',
  path: '/full-stack',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/full-stack': typeof ServicesFullStackRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/staffing': typeof ServicesStaffingRoute
  '/services/testing': typeof ServicesTestingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/services/full-stack': typeof ServicesFullStackRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/staffing': typeof ServicesStaffingRoute
  '/services/testing': typeof ServicesTestingRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/full-stack': typeof ServicesFullStackRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/staffing': typeof ServicesStaffingRoute
  '/services/testing': typeof ServicesTestingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/services'
    | '/services/full-stack'
    | '/services/mobile'
    | '/services/staffing'
    | '/services/testing'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/services/full-stack'
    | '/services/mobile'
    | '/services/staffing'
    | '/services/testing'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/services'
    | '/services/full-stack'
    | '/services/mobile'
    | '/services/staffing'
    | '/services/testing'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/testing': {
      id: '/services/testing'
      path: '/testing'
      fullPath: '/services/testing'
      preLoaderRoute: typeof ServicesTestingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/staffing': {
      id: '/services/staffing'
      path: '/staffing'
      fullPath: '/services/staffing'
      preLoaderRoute: typeof ServicesStaffingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mobile': {
      id: '/services/mobile'
      path: '/mobile'
      fullPath: '/services/mobile'
      preLoaderRoute: typeof ServicesMobileRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/full-stack': {
      id: '/services/full-stack'
      path: '/full-stack'
      fullPath: '/services/full-stack'
      preLoaderRoute: typeof ServicesFullStackRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesFullStackRoute: typeof ServicesFullStackRoute
  ServicesMobileRoute: typeof ServicesMobileRoute
  ServicesStaffingRoute: typeof ServicesStaffingRoute
  ServicesTestingRoute: typeof ServicesTestingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesFullStackRoute: ServicesFullStackRoute,
  ServicesMobileRoute: ServicesMobileRoute,
  ServicesStaffingRoute: ServicesStaffingRoute,
  ServicesTestingRoute: ServicesTestingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
